# Happy Coding!

service: dynamodb-trigger-cache-hydrator

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: YOUR_TABLE
    REDIS_HOST: !ImportValue YOUR_REDIS_HOST
    REDIS_PORT: 6379
    REDIS_TTL: 43200 # 12 hours - you might want to change this
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
        - dynamodb:BatchGetItem
      Resource:
        - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}

functions:
  process:
    handler: handler.process
    description: Hydrates Cache # you might want to change this
    reservedConcurrency: 10
    events:
      - stream:
          type: dynamodb
          arn:
            !ImportValue YOUR_TABLE_STREAM_ARN
